# Generated by Django 5.2.1 on 2025-05-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
